### ISSUE TITLE
[324] The validation of media ids failed.

### ISSUE THREAD

**Issue by chrisloftus** [thujohn/twitter#114]
I'm trying to simply tweet with an image and get this error:

`[324] The validation of media ids failed.`

Tweeting without media works perfectly fine. It seems to be failing on posting the tweet with media id.

This is my code:

```php
$uploaded_media = Twitter::uploadMedia(['media' => File::get(public_path() . '/images/logo.png')]);

Twitter::postTweet(['status' => 'Tweet with an image.', 'media_ids' => $uploaded_media->media_id_string]);
```

I can't get any size image to work, be it in dimensions or file size. I've tried everything.

**Comment by chrisloftus** [comment]
Problem solved: I was using a different access token for uploading and posting the tweet.

**Comment by maharajay** [comment]
lol  it is not working it is only posting the content except media

**Comment by maharajay** [comment]
> Problem solved: I was using different access tokens for uploading and posting the tweet.
lol it is not working it is only posting the content except media
