### ISSUE TITLE
[64] The Twitter REST API v1 is no longer active. Please migrate to API v1.1

### ISSUE THREAD

**Issue by crmolinaz** [thujohn/twitter#188]
Hi,

I'm using the library with Laravel version 5.2.45 and i receive this error when i try to post. I dont know if im doing something wrong, but in the config file the version for the API is 1.1

**Comment by crmolinaz** [comment]
i found the solution, the function postTweetMedia is now deprecated. Please remove it from the project.

**Comment by ArthurBugan** [comment]
If this is deprecated, How am I going to upload an image to use on my tweet?

**Comment by crmolinaz** [comment]
you first need to upload the image with the function : Twitter::uploadMedia, this function return the media_id.

After that, you call this function : Twitter::postTweet, that receive an array as arguments. For images use media_ids => array(media_id_uploaded_previously)

if you still have questions, i can send you an example.

**Comment by ArthurBugan** [comment]
Thats the way I AM doing It, I Will post my code gere in some minutes Just turn on my pc

**Comment by ArthurBugan** [comment]
`
    if($numImage > 0){ 
        for($i=0;$i<$numImage;$i++){
            $image_name[$i] = $image[$i]->arquivo;

            $photoId[$i] = Twitter::uploadMedia(['media' => File::get(public_path("anexos/{$image_name[$i]}"))]);
            var_dump($photoId[$i]); //Here I have this error: "{"error":"[100] Unknown error"}"
            exit();
        }`

**Comment by crmolinaz** [comment]
$id_uploaded_media = Twitter::uploadMedia(['media' => File::get($fileAbsolutePath)]);
Twitter::postTweet(['status' => 'here my message', 'media_ids' => array($id_uploaded_media), 'format' => 'json']);

That's my example, and it works (i tested 5 minutes ago in twitter), i think you have another problem that its not related to the library.

**Comment by ArthurBugan** [comment]
Yeah I think so. Thanks anyway!

**Comment by ArthurBugan** [comment]
Could U post how u create the $fileAbsolutePath variable?

**Comment by crmolinaz** [comment]
$fileAbsolutePath = public_path('img/assets/' . $user->id . '/h_' . $user->profile_img);

i will suggest, debug the File::get(public_path("anexos/{$image_name[$i]}") , probably the file doesn't exists.

**Comment by ArthurBugan** [comment]
I did like create, I put the path of the file in a variable and passed to File::get, still didnt work,but i ran a If(file_exists()) and it returns true, So my file is there, this code was working and i even tried to run an older version from git that i have but it shows the same error

**Comment by crmolinaz** [comment]
my config file

// You can find the keys here : https://apps.twitter.com/

return [
	'debug'               => false,

	'API_URL'             => 'api.twitter.com',
	'UPLOAD_URL'          => 'upload.twitter.com',
	'API_VERSION'         => '1.1',
	'AUTHENTICATE_URL'    => 'https://api.twitter.com/oauth/authenticate',
	'AUTHORIZE_URL'       => 'https://api.twitter.com/oauth/authorize',
	'ACCESS_TOKEN_URL'    => 'https://api.twitter.com/oauth/access_token',
	'REQUEST_TOKEN_URL'   => 'https://api.twitter.com/oauth/request_token',
	'USE_SSL'             => true,

	'CONSUMER_KEY'        => function_exists('env') ? env('TWITTER_CONSUMER_KEY', '') : '',
	'CONSUMER_SECRET'     => function_exists('env') ? env('TWITTER_CONSUMER_SECRET', '') : '',
	'ACCESS_TOKEN'        => function_exists('env') ? env('TWITTER_ACCESS_TOKEN', '') : '',
	'ACCESS_TOKEN_SECRET' => function_exists('env') ? env('TWITTER_ACCESS_TOKEN_SECRET', '') : '',
];

**Comment by ArthurBugan** [comment]
I can consume from the api, because i'm retrieving the user profile in another part of the code and its working, if i try to make a tweet with only text it works too!
