### ISSUE TITLE
Could not authenticate you . error code 32

### ISSUE THREAD

**Issue by hassan-khalil** [thujohn/twitter#216]
i am getting this error 

`{"errors":[{"code":32,"message":"Could not authenticate you."}]}`
code was working by yesterday. but  now its not working . i have regenerated the app token and secret checked the configuration but i dont know what is the problem  . 

screen shot 
![screenshot_2](https://user-images.githubusercontent.com/20831567/32830029-be0c5dfa-ca15-11e7-834f-5d41cc80c598.png)

**login code** 
`               $sign_in_twitter = true;
		$force_login = false;
         
        	\Twitter::reconfig(['token' => '', 'secret' => '']);
		try{
			$token = \Twitter::getRequestToken(route('twitter.callback'));
			
		}catch(Exception $exp){
			 self::logError($exp, __CLASS__, __METHOD__);
               return  back()->with([
                            'serverError' => trans('messages.error.server_error')
                ]);	
		}

		if (isset($token['oauth_token_secret']))
		{
			$url = \Twitter::getAuthorizeURL($token, $sign_in_twitter, $force_login);

			Session::put('oauth_state', 'start');
			Session::put('oauth_request_token', $token['oauth_token']);
			Session::put('oauth_request_token_secret', $token['oauth_token_secret']);

			return Redirect::to($url);
		}

		return Redirect::route('accounts')->with(['serverError' => trans('messages.error.login_error')]);`

**Callback method**

				$request_token = [
					'token'  => Session::get('oauth_request_token'),
					'secret' => Session::get('oauth_request_token_secret'),
				];

				\Twitter::reconfig($request_token);

				$oauth_verifier = false;

				if ($request->has('oauth_verifier'))
				{
					$oauth_verifier = $request->get('oauth_verifier');
					// getAccessToken() will reset the token for you
					$token = \Twitter::getAccessToken($oauth_verifier);
				}

				if (!isset($token['oauth_token_secret']))
				{
					return Redirect(url('accounts'))->with(['serverError' => trans('messages.error.login_error')]);
				}

				$credentials = \Twitter::getCredentials();

				if (is_object($credentials) && !isset($credentials->error))
				{
					(new Accounts())->fill($credentials)->setToken(array_get($token,'oauth_token'))->setSecret(array_get($token,'oauth_token_secret'))->save();
				 	Session::put('access_token', $token);
				       return Redirect(url('accounts'))->with(['success' => trans('messages.success.twitter_account_added')]);
				}
			}
			return Redirect(url('accounts'))->with(['serverError' => trans('messages.error.server_error')]);

**Comment by loranger** [comment]
I got the same issue. What was your solution ?

**Comment by hassan-khalil** [comment]
the problem was in **CONSUMER_KEY** and **CONSUMER_SECRET**  in config file . maybe some character were missing  in config . at first i didn't know that . then i deleted the app . created new app from twitter . and replace the CONSUMER_KEY , and CONSUMER_SECRET.

 it solved my problem.

**Comment by loranger** [comment]
Ok, that was an issue alike. Thanks !

**Comment by ronlinet** [comment]
In my case I had to clear the configuration cache : 
`php artisan config:clear`
