### ISSUE TITLE
Multiple Config Credentials

### ISSUE THREAD

**Issue by furkankadioglu** [thujohn/twitter#226]
**Can we change this credentials dynamically?**

TWITTER_CONSUMER_KEY
TWITTER_CONSUMER_SECRET
TWITTER_ACCESS_TOKEN
TWITTER_ACCESS_TOKEN_SECRET

**Comment by mohitpawar10** [comment]
You can just define the array of credentials, check if the limit of any credentials is met. if max limit of any credentials is met use another one. I don't think so this would be the good approach. If you want to increase limit you can fetch more data in the single request so you don't run of out requests limit. Why do you want to use different credentials?
