### ISSUE TITLE
Fetch more than 15 results with getSearch

### ISSUE THREAD

**Issue by tbergeron** [thujohn/twitter#31]
I'm trying to fetch _all_ statuses containing a certain hashtag for a contest.

``` php
$tweets = Twitter::getSearch([
    'q' => '#ff', // using #ff for testing
    'until' => '2014-06-07',
    'rpp' => 100,
    'result_type' => 'recent'
]);
```

In docs, it says we can specify a `rpp` parameter to fetch up to 100 statuses. I tried it but unfortunately it doesn't retrieve more than 15 tweets at a time.

I also noticed there's a `page` parameter so I guess I could loop and fetch all of them that way but still I'd like to request more than 15 at a time.

NB: I'm using `until` to get all the entries up to a certain date. I'd like to specify a time but I didn't see anything about it in the API docs though.

Could somebody please tell me what is wrong that is preventing me to fetch 100 statuses in one request?

Thanks and have a nice weekend!

**Comment by HeathNaylor** [comment]
Apparently you are supposed to be able to use max_id and since_id to control which tweets you want, however I can not get this to work.

https://dev.twitter.com/rest/public/timelines

**Comment by ronlinet** [comment]
@thujohn the not by @HeathNaylor  is correct there is apparently missing max_id an since_id feature. Is this going be implemented ?
