### ISSUE TITLE
Using thujohn/twitter with philo/twitter

### ISSUE THREAD

**Issue by nrs365** [thujohn/twitter#35]
I'm writing a Laravel 4 app that uses the getUserTime function of Thujohn (and works wonderfully) but for another aspect of my app, I'm using philo/twitter's oauth (which also works very well).  The problem is that the namespaces for both of the packages are the same.  Do you have any suggestions on how to get the Thujohn package to be recognized specifically for the functions I need it for and have function calls get confused with the philo/twitter package?  I tried renaming the alias, hardcoding the use in the controllers, etc.  If it could be a clue to help you help me, I have noticed that when I reverse the order of the package listing in config/app.php that the opposite package will start working.
Any advice would be much appreciated!  Thanks!!

**Comment by pbarrientosc** [comment]
xx

**Comment by pbarrientosc** [comment]
xx

**Comment by pbarrientosc** [comment]
xxxxx
