### ISSUE TITLE
Exclude_replies breaks the counting part

### ISSUE THREAD

**Issue by Jaspur** [thujohn/twitter#4]
When you exclude mentions, the count doesn't work anymore:

`$timeline = Twitter::getUserTimeline(array('screen_name' => 'foobar', 'count' => 3, 'exclude_replies' => true));`

In my case at the moment, I only have one tweet in my response, because of the excluding of replies (the last two tweets are replies).

**Comment by developer239** [comment]
How do I solve this problem though?

**Comment by jlimahaverford** [comment]
Exactly.  What is the point of including this option if it's not properly supported?  This just means there are hundreds of developers around the world coding up workarounds to pull N tweets excluding replies/retweets and using inefficient access patterns through the TwitterAPI to achieve this!
