### ISSUE TITLE
postTweetMedia

### ISSUE THREAD

**Issue by freimanas** [thujohn/twitter#41]
Hi,

Was trying to post an image to a tweet, but without any luck yet. Have read the twitter API docs I can see this:
This end point has been deprecated. Please refer to Uploading Media: Multiple Photos for uploading one or more media entities.
https://dev.twitter.com/rest/reference/post/statuses/update_with_media

any chance to update the code to reflect this?

thanks

**Comment by thujohn** [comment]
This will be in the next version wich is coming soon.

**Comment by yhbyun** [comment]
Today, I updated twitter package and met 'postTweetMedia' method error. I am looking forward the next version to fix the error. 

Anyway, thanks for your good work.

**Comment by thujohn** [comment]
Hi.

This method is deprecated : https://dev.twitter.com/rest/reference/post/statuses/update_with_media

I added an example for uploading a media : https://github.com/thujohn/twitter#examples

**Comment by yhbyun** [comment]
The problem is solved. Thanks.
