### ISSUE TITLE
Class 'App\Http\Controllers\Twitter' not found

### ISSUE THREAD

**Issue by joearcher** [thujohn/twitter#75]
Using Laravel v5.0.22

I have followed the installation instructions, it would appear that the class is being loaded, as I do not get an error complaining about the ServiceProvider, but it seems that the Facade does not resolve to the class.

Any ideas?

**Comment by thujohn** [comment]
Because of namespace in your controller it will search Twitter in the same folder.
Solution : ```use \Twitter;```

**Comment by joearcher** [comment]
Jesus, I am so dumb. Thanks.
