### ISSUE TITLE
Access methods in controllers

### ISSUE THREAD

**Issue by barisozanguler** [thujohn/twitter#76]
Hi,

I am new on laravel. We will use Twitter::(method) in routes.php but i want use in controllers. How can i do that ? I searched injection somewhere for this but not found.

Thanks.

**Comment by thujohn** [comment]
Hi.

Simply add ```use Twitter;``` or use ```\Twitter```

**Comment by barisozanguler** [comment]
I was tried `use 'Thujohn\Twitter\Twitter';` :)

Thanks `use Twitter;` worked.
