### ISSUE TITLE
Errors without any reason (just only sometimes)

### ISSUE THREAD

**Issue by BrainBuzzer** [thujohn/twitter#88]
Hi. I am creating a app with this api. When I try to get the user's screen, I get error saying `undefined index: errorno on line 266 Twitter.php` the code works fine after refreshing but shows this error sometimes. Please help.

**Comment by cilsilver** [comment]
Having similar issues on laravel 4.2

**Comment by EmilioBravo** [comment]
Same issue over here, laravel 4.2

**Comment by zerojargon** [comment]
on Twitter.php, line 266, there's the following line

    $this->log('ERROR_CODE : '.$response['errorno']);

I believe it needs to be as follows

    $this->log('ERROR_CODE : '.$response['errno']);

This is in the following pull request:

https://github.com/thujohn/twitter/pull/96
