### ISSUE TITLE
Getting 'Class 'Thujohn\Twitter\TwitterFacade' not found' Laravel 4 and thujohn/twitter ~2.0

### ISSUE THREAD

**Issue by salaria** [thujohn/twitter#93]
Getting 'Class 'Thujohn\Twitter\TwitterFacade' not found' using Laravel 4 and "thujohn/twitter": "~2.0", in conf.

Stack Trace:
` exception 'ErrorException' with message 'Class 'Thujohn\Twitter\TwitterFacade' not found' in /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:64
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'Class 'Thujohn\\...', '/var/www/html/v...', 64, Array)
#1 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php(64): class_alias('Thujohn\\Twitter...', 'Twitter')
#2 [internal function]: Illuminate\Foundation\AliasLoader->load('Twitter')
#3 /var/www/html/vfdev/app/controllers/StudioSocialController.php(498): spl_autoload_call('Twitter')
#4 [internal function]: StudioSocialController->saveTwitterSettings()
#5 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('saveTwitterSett...', Array)
#7 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(StudioSocialController), Object(Illuminate\Routing\Route), 'saveTwitterSett...')
#8 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'StudioSocialCon...', 'saveTwitterSett...')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#11 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/vfdev/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/vfdev/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#20 /var/www/html/vfdev/public/index.php(49): Illuminate\Foundation\Application->run()
#21 {main} [] []`

**Comment by csgt** [comment]
See the section: "Upgrading from 1.1".  You have to change the Facade name...
