### ISSUE TITLE
Linkify thinks .@username is an email address

### ISSUE THREAD

**Issue by tremby** [thujohn/twitter#99]
Due to a bad regex, `.@username`, which appears at the beginning of some tweets (tweeting at a particular person, but not wanting to hide it from feed), is treated as an email address.

This may be low priority since if #64 is seen through this bug would likely disappear.

**Comment by thujohn** [comment]
Hi.

It would be solved now.

**Comment by tremby** [comment]
Likely is. But the regex https://github.com/thujohn/twitter/commit/0cb480f93b2f26ff6f945c114464dee8042f7bf9#diff-811db7ec3335c2840e32d209f1fc8cb4R334 is still bad. It'll miss any email addresses with TLDs longer than three characters long, for example the .travel and .cool TLDs, which I've increasingly seen used recently. Maybe not a huge deal, but it's another reason to look at #64. Also see my comment on that ticket.
